WRR-1005: Updated Eslint to version 9
enactjs/eslint-config-enact pull request #92
Opened 2024-11-28 12:41 UTC by daniel-stoian-lgp

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] I have run automated CLI testing and it is passed
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Support for eslint 8 was dropped and Eslint 9 was released

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Update Eslint to version 9 and eslint related modules to latest versions

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
Until full support for flat config is available, we need to set an env variable to false. That required the adding of an extra dependency `cross-env`.

### Links
[//]: # (Related issues, references)
WRR-1005

### Comments
Enact-DCO-1.0-Signed-off-by: Daniel Stoian (daniel.stoian@lgepartner.com)

2024-11-29 14:37 UTC, stanca-pop-lgp requested changes

2024-11-29 14:37 UTC, stanca-pop-lgp commented on CHANGELOG.md
> +*
```suggestion
* Updated Enact ESLint config to `9.1.5` including eslint related modules.

```

2024-12-03 07:45 UTC, stanca-pop-lgp approved these changes

2025-02-20 01:56 UTC, hong6316 approved these changes
👍

2025-02-20 01:57 UTC, merged

2025-02-20 05:01 UTC, hong6316 commented on index.js
> +				...globals.node,
I have a question but, is there any reason of adding `globals.node` ?
This config file doesn't have this option before.